name: 'Common Setup'
description: 'Common setup steps for build related workflows'
inputs:
  # Seems we can't use secrets in action.yml
  DOCKER_USER:
    description: 'Docker Hub username'
    required: true
  DOCKER_TOKEN:
    description: 'Docker Hub password'
    required: true
outputs:
  platforms:
    description: 'Available platforms'
    value: ${{ steps.buildx.outputs.platforms }}
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # pin@v3
    - uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # pin@v3
      id: buildx
    - name: Log in to Docker Hub
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # pin@v3
      with:
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ inputs.DOCKER_TOKEN }}
