name: 'Common Setup'
description: 'Common setup steps for build related workflows'
inputs: # Seems we can't use secrets in action.yml
  DOCKER_USER:
    description: 'Docker Hub username'
    required: true
  DOCKER_TOKEN:
    description: 'Docker Hub password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # pin@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # pin@v1
    - uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # pin@v1
      id: buildx
    - name: Set output
      run: |
        echo "platforms=${{ steps.buildx.outputs.platforms }}" >> $GITHUB_OUTPUT
        echo "Github output: $GITHUB_OUTPUT"
        cat $GITHUB_OUTPUT
      shell: bash
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ inputs.DOCKER_TOKEN }}
