name: 'Common Setup'
description: 'Common setup steps for build related workflows'
inputs: # Seems we can't use secrets in action.yml
  DOCKER_USER:
    description: 'Docker Hub username'
    required: true
  DOCKER_TOKEN:
    description: 'Docker Hub password'
    required: true
outputs:
  platforms:
    description: 'Available platforms'
    value: ${{ steps.buildx.outputs.platforms }}
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      id: buildx
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ inputs.DOCKER_TOKEN }}
