name: go-checks

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v4
      - name: Setup Go environment
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # pin@v5
        with:
          go-version: '1.22.2'
          check-latest: true
      - name: Run Vulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
      - name: Download linter config
        run: curl -fsS -o .golangci.yml https://raw.githubusercontent.com/fortio/workflows/main/golangci.yml
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # pin@v3
      - name: Optional init
        run: make dependencies || true # Used in fortio for instance to prep for go tests
      - name: Run tests with race detector
        run: |
          go version
          go run . buildinfo || true # to also confirm go toolchain version used
          go test -race ./...
