name: Release

on:
  workflow_call:
    inputs:
      description:
        description: 'Description of the project for the goreleaser tap'
        required: false
        type: string
        default: ''
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true
      GH_PAT:
        required: true
  push:
    tags:
      # so a vX.Y.Z-test1 doesn't trigger build
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-pre'
      - 'v[0-9]+.[0-9]+.[0-9]+\+'
  pull_request:
    # To test
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Common Setup
        id: common_setup
        uses: fortio/workflows/.github/actions/common_setup@main # change back to @main after testing changes in a branch
        with:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: Available platforms
        run: |
          echo "Platforms found: ${{ steps.common_setup.outputs.platforms }}"
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # pin@v5
        with:
          go-version: '1.22'
          check-latest: true
      - name: Download goreleaser config
        run: curl -fsS -o .goreleaser.yaml https://raw.githubusercontent.com/fortio/workflows/main/goreleaser.yaml
      - name: "GoReleaser Action"
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # pin@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          TAP_DESCRIPTION: ${{ inputs.description }}
          GOWORK: off
